### ISSUE TITLE
18362 admin login issue.

### ISSUE THREAD

**Issue by apple3000** [slorelee/wimbuilder2#12]
1. builder didn't copy "pecmdadmin.ini" to target
2. 18362 build, For admin login
 2-1)Needs "Windows.Globalization.Fontgroups.dll". if not, has black screen with mouse.
2-2)"X:\users\Administrator.WINXPE" account created. what's problem?
Thank you for your affort. regards.

**Comment by slorelee** [comment]
Hi, @apple3000

thanks for report.

> builder didn't copy "pecmdadmin.ini" to target

I moved Pecmd.ini, PecmdAdmin.ini to _CustomFiles_, but not complated commit that. 
check out/download the latest version will be fixed.

>2-1)Needs "Windows.Globalization.Fontgroups.dll". if not, has black screen with mouse.

has black screen with mouse.  > because problem 1. there is no pecmdadmin.ini.
I tested 10.0.18362(zh-CN) without "Windows.Globalization.Fontgroups.dll".

2-2)"X:\users\Administrator.WINXPE" account created. what's problem?

some commands make X:\Users\Administrator\AppData\Cache folder,
that when new Administrator home dir creating, it create a new one with computername.

but this problem have been fixed.

Would you try the new version? (WimBuilder - v2019.03.27.7a8268e5)

**Comment by apple3000** [comment]
thanks. i have not tested 03.27 but thank to your solution.
2-1 is ok. you're right.
2-2 was my fault.
i removed "//" in //REGI HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\S-1-5-18\ProfileImagePath=X:\Users\Administrator

i will try new version some day later.
