### ISSUE TITLE
when use slim or slim extra script, black screen

### ISSUE THREAD

**Issue by apple3000** [slorelee/wimbuilder2#13]
maybe when I use korean IME, when enter to desktop, just see black screen and mouse point.
IF I must solve this, needs Faultrep.dll and mui.

**Comment by slorelee** [comment]
Thanks for report.

`za-Slim/main_Ultra.bat:del /a /f /q "%X_SYS%\Faultrep.dll"`

Enable slim-ultra option will delete the file.

I use **Windows 10 Pro (10.0.18362,x64,ko-KR)**, couldn't get IME work,
and I can't reproduce the problem.

if you delete the line in za-Slim/main_Ultra.bat, and the issue is fixed, please tell me,
I will comment out it.

BTW, I don't know the Fonts required in korean system, so SlimExtra option will Keep fonts for English,
that causes the display problem of korean characters.

**Comment by slorelee** [comment]
I tested that:
Enable Admin account + IME will get black screen. (without slim)
There are Faultrep.dll and ko-KR\Faultrep.dll.mui files.

korean IME's problem is hard for me ...

**Comment by slorelee** [comment]
miss Windows.Globalization.Fontgroups.dll for enabling Administrator feature.
Try the new version please.

**Comment by apple3000** [comment]
> Thanks for report.
> 
> `za-Slim/main_Ultra.bat:del /a /f /q "%X_SYS%\Faultrep.dll"`
> 
> Enable slim-ultra option will delete the file.
> 
> I use **Windows 10 Pro (10.0.18362,x64,ko-KR)**, couldn't get IME work,
> and I can't reproduce the problem.
> 
> if you delete the line in za-Slim/main_Ultra.bat, and the issue is fixed, please tell me,
> I will comment out it.
> 
> BTW, I don't know the Fonts required in korean system, so SlimExtra option will Keep fonts for English,
> that causes the display problem of korean characters.

here is Ime_ko-KR.bat. 
[https://pastebin.com/b10cYbSv](url)

I changed by this. 
because when i build with your korean ime.bat, korean/english keyboard button did not work. 
It just means that IME toggle did not change at rignt corner when i pressed keyboard key.
but I can write korean, and english.
